<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class EmployeesTemplateExport implements FromArray, WithHeadings, WithStyles, WithColumnWidths
{
    public function array(): array
    {
        return [
            [
                'EXPO 2024',
                'John',
                'Michael',
                'Doe',
                'john.doe@company.com',
                'john.personal@email.com',
                '+1234567890',
                '+1',
                '+0987654321',
                '+1',
                '',
                'AGR-2024-001',
                '123456789',
                'Mr.',
                'Male',
                'Married',
                'Senior Product Manager',
                'Engineering',
                'Technology',
                'Innovation',
                'Senior Level',
                'Main Entity',
                'Full Time',
                'Permanent',
                'Monthly',
                '2024-01-15',
                '2026-12-31',
                '1985-03-20',
                'New York',
                'United States',
                '2024-01-15',
                '2024-01-15',
                'Company Sponsored',
                'Company Sponsor',
                'American',
                'P123456789',
                '2030-12-31',
                '2028-06-30',
                'Y',
                'N',
            ],
            [
                'EXPO 2024',
                'Jane',
                'Marie',
                'Smith',
                'jane.smith@company.com',
                'jane.smith@email.com',
                '+1234567891',
                '+1',
                '',
                '',
                '',
                'AGR-2024-002',
                '987654321',
                'Ms.',
                'Female',
                'Single',
                'UX Designer',
                'Design',
                'Product',
                'User Experience',
                'Mid Level',
                'Main Entity',
                'Full Time',
                'Permanent',
                'Monthly',
                '2024-02-01',
                '2027-01-31',
                '1990-07-15',
                'London',
                'United Kingdom',
                '2024-02-01',
                '2024-02-01',
                'Self Sponsored',
                'Self Sponsored',
                'British',
                'GB987654321',
                '2029-08-15',
                '2027-12-31',
                'N',
                'N',
            ],
            [
                'Tech Summit 2025',
                'Ahmed',
                'Ali',
                'Hassan',
                'ahmed.hassan@company.com',
                '',
                '+1234567892',
                '+965',
                '+1234567893',
                '+965',
                '',
                'AGR-2024-003',
                '456789123',
                'Mr.',
                'Male',
                'Married',
                'Software Engineer',
                'Engineering',
                'Technology',
                'Development',
                'Junior Level',
                'Main Entity',
                'Contract',
                'Contractor',
                'Daily',
                '2024-03-01',
                '2027-02-28',
                '1988-11-30',
                'Kuwait City',
                'Kuwait',
                '2024-03-01',
                '2024-03-01',
                'Company Sponsored',
                'Company Sponsor',
                'Kuwaiti',
                'KW456789123',
                '2031-05-20',
                '2029-03-15',
                'N',
                'Y',
            ],
        ];
    }

    public function headings(): array
    {
        return [
            'Event Name',
            'First Name',
            'Middle Name',
            'Last Name',
            'Work Email',
            'Personal Email',
            'Phone Number',
            'Phone Area Code',
            'Alt Phone Number',
            'Alt Area Code',
            'Employee Number (Optional - Auto-generated)',
            'Agreement Number',
            'National ID',
            'Salutation',
            'Gender',
            'Marital Status',
            'Designation',
            'Department',
            'Directorate',
            'Functional Area',
            'Job Level',
            'Entity',
            'Contract Type',
            'Employee Type',
            'Salary Basis',
            'Contract Start Date',
            'Contract End Date',
            'Date of Birth',
            'Town of Birth',
            'Country of Birth',
            'Date of Hire',
            'Join Date',
            'Sponsorship Type',
            'Sponsorship Name',
            'Nationality',
            'Passport Number',
            'Passport Expiry',
            'Civil ID Expiry',
            'Manager Flag',
            'Admin Flag',
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => [
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => [
                    'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '4F46E5'],
                ],
            ],
        ];
    }

    public function columnWidths(): array
    {
        return [
            'A' => 15,
            'B' => 15,
            'C' => 15,
            'D' => 25,
            'E' => 25,
            'F' => 15,
            'G' => 15,
            'H' => 15,
            'I' => 18,
            'J' => 15,
            'K' => 12,
            'L' => 12,
            'M' => 15,
            'N' => 20,
            'O' => 15,
            'P' => 15,
            'Q' => 18,
            'R' => 18,
            'S' => 18,
            'T' => 18,
            'U' => 15,
            'V' => 15,
            'W' => 15,
            'X' => 18,
            'Y' => 15,
            'Z' => 18,
            'AA' => 15,
            'AB' => 15,
            'AC' => 12,
            'AD' => 12,
        ];
    }
}
